FROM emuframework-local:1.0.2-test
HEALTHCHECK --interval=1s --timeout=1s --start-period=1s --retries=2 CMD node -e "process.exit(1)"
CMD ["node", "-e", "require('node:fs').appendFileSync('/data/data.db',Buffer.from('EMUTEST_CORRUPTION'));setInterval(()=>{},1000)"]
