import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { FastifyInstance } from 'fastify';
import type { AnyMeta, Kernel } from '@emu/core';
import { buildServer } from '../src/server.js';
import { applyErpSample } from './fixtures/erpSample.js';
import { completeTestSetup, TEST_ADMIN_PASSWORD, TEST_SETUP_CODE } from './setupHelper.js';

describe('localized metadata and navigation preferences',()=>{
  let app:FastifyInstance;let kernel:Kernel;let auth:{cookie:string};
  beforeAll(async()=>{app=buildServer({setupCode:TEST_SETUP_CODE});await app.ready();await completeTestSetup(app);kernel=(app as FastifyInstance&{kernel:Kernel}).kernel;applyErpSample(kernel);const stored=kernel.designerContext().select('FW_WebArtifact').toArray().map((row)=>JSON.parse(String(row.f.json)) as AnyMeta);const translation:AnyMeta={kind:'translation',name:'ERP_Thai',app:'erp',model:'MiniERPApplication',layer:'SYS',locale:'th',resources:{'app.erp.label':'อีอาร์พี','table.ERP_CustTable.label':'ลูกค้า','table.ERP_CustTable.field.name.label':'ชื่อลูกค้า'}};expect(kernel.applyWebArtifacts([...stored,translation])).toEqual([]);const login=await app.inject({method:'POST',url:'/api/login',payload:{username:'admin',password:TEST_ADMIN_PASSWORD}});auth={cookie:(login.headers['set-cookie'] as string).split(';')[0]};});
  afterAll(()=>app.close());
  it('uses exact locale then base language and preserves default labels',async()=>{expect((await app.inject({method:'PATCH',url:'/api/me/locale',headers:auth,payload:{locale:'th-TH'}})).statusCode).toBe(200);const metadata=(await app.inject({method:'GET',url:'/api/metadata',headers:auth})).json();expect(metadata.locale).toBe('th-TH');expect(metadata.apps.find((entry:any)=>entry.name==='erp').label).toBe('อีอาร์พี');const customer=metadata.tables.find((entry:any)=>entry.name==='ERP_CustTable');expect(customer.label).toBe('ลูกค้า');expect(customer.fields.find((field:any)=>field.name==='name').label).toBe('ชื่อลูกค้า');expect(customer.fields.find((field:any)=>field.name==='phone').label).toBe('Phone');});
  it('stores favorites and only ten recent authorized stable menu items',async()=>{const metadata=(await app.inject({method:'GET',url:'/api/metadata',headers:auth})).json();const menu=metadata.apps.find((entry:any)=>entry.name==='erp').menus[0];const leaves:any[]=[];const visit=(items:any[])=>items.forEach((item)=>item.items?.length?visit(item.items):leaves.push(item));visit(menu.items);const item=leaves[0];expect(item.id).toBeTruthy();expect((await app.inject({method:'PUT',url:`/api/navigation/favorites/${encodeURIComponent(menu.name)}/${encodeURIComponent(item.id)}`,headers:auth,payload:{favorite:true}})).statusCode).toBe(200);await app.inject({method:'POST',url:'/api/navigation/recent',headers:auth,payload:{menuName:menu.name,itemId:item.id}});const prefs=(await app.inject({method:'GET',url:'/api/navigation/preferences',headers:auth})).json();expect(prefs.favorites).toEqual([expect.objectContaining({menuName:menu.name,itemId:item.id})]);expect(prefs.recent).toHaveLength(1);});
});
