/** Framework UI message catalog shipped as system TranslationMeta artifacts.
 * Keys use the reserved `ui.*` namespace; only the system app may define them. */

export const FRAMEWORK_UI_EN: Record<string, string> = {
  'ui.nav.settings': 'Settings',
  'ui.nav.recent': 'Recent',
  'ui.nav.recentEmpty': 'No recently opened items',
  'ui.nav.openMenu': 'Open navigation',
  'ui.nav.collapseMenu': 'Collapse navigation',
  'ui.nav.systemMaintenance': 'System Maintenance',
  'ui.nav.appData': 'App Data Management',
  'ui.nav.reportFonts': 'Report Fonts',
  'ui.nav.smtp': 'SMTP Settings',
  'ui.nav.usersSecurity': 'Users & Security',
  'ui.nav.changePassword': 'Change Password',
  'ui.auth.logout': 'Sign out',
  'ui.auth.changePassword': 'Change password',
  'ui.auth.language': 'Language',
  'ui.auth.localeSaved': 'Language updated',
  'ui.auth.localePartial': 'Language saved, but reloading texts failed',
  'ui.home.title': 'Apps',
  'ui.home.subtitle': 'Choose an app to continue your work.',
  'ui.home.emptyTitle': 'Build your first business app',
  'ui.home.emptyDescription': 'Start with an entity, fields, page, and navigation. No JSON required.',
  'ui.home.create': 'Create your first app',
  'ui.common.save': 'Save',
  'ui.common.back': 'Back',
  'ui.common.cancel': 'Cancel',
  'ui.common.delete': 'Delete',
  'ui.common.close': 'Close',
  'ui.common.download': 'Download',
  'ui.common.search': 'Search',
  'ui.common.retry': 'Retry',
  'ui.common.unknown': 'Unknown',
  'ui.attachments.title': 'Attachments',
  'ui.attachments.upload': 'Upload file',
  'ui.attachments.notePlaceholder': 'Add a note',
  'ui.attachments.addNote': 'Add note',
  'ui.attachments.urlPlaceholder': 'https://…',
  'ui.attachments.addUrl': 'Add URL',
  'ui.attachments.empty': 'No attachments',
  'ui.attachments.deleteConfirm': 'Delete this attachment?',
  'ui.attachments.uploaded': 'Attachment uploaded',
  'ui.attachments.preview': 'Open preview',
  'ui.attachments.previewFailed': 'The image could not be loaded',
  'ui.attachments.imageAlt': 'Image preview',
  'ui.maintenance.title': 'System Maintenance',
  'ui.maintenance.subtitle': 'Update the framework and create verified recovery points.',
  'ui.maintenance.update': 'Framework update',
  'ui.maintenance.current': 'Current',
  'ui.maintenance.latest': 'Latest',
  'ui.maintenance.deployment': 'Deployment',
  'ui.maintenance.lastChecked': 'Last checked',
  'ui.maintenance.notChecked': 'Not checked',
  'ui.maintenance.checkUpdate': 'Check for updates',
  'ui.maintenance.updateLatest': 'Update to latest stable',
  'ui.maintenance.upToDate': 'Framework is up to date',
  'ui.maintenance.updateStarted': 'Backup created. Framework update started.',
  'ui.maintenance.updateDisabled': 'Web update is not configured for this deployment. Use the manual update guide.',
  'ui.maintenance.updateTitle': 'Update framework?',
  'ui.maintenance.updateConfirm': 'Create backup and update',
  'ui.maintenance.updateBody': 'The app will create a verified backup, install the latest version, and restart. Users will briefly lose access. Do not close or power off the host during the update.',
  'ui.maintenance.backup': 'Database backup',
  'ui.maintenance.backupDescription': 'Create checksummed recovery packages or restore selected system components entirely from this page.',
  'ui.maintenance.backupComponent': 'Data to back up',
  'ui.maintenance.backupComponentHint': 'Select a component and press Download Backup to start. Upload & Restore uses the components inside the uploaded package.',
  'ui.maintenance.downloadBackup': 'Download Backup',
  'ui.maintenance.uploadRestore': 'Upload & Restore',
  'ui.maintenance.backupReady': 'Ready to restore',
  'ui.maintenance.restoreStarted': 'Restore started. The app will restart automatically.',
  'ui.maintenance.restoreBody': 'The app will become unavailable briefly. Selected components are replaced atomically and rolled back if the restart health check fails.',
  'ui.maintenance.restoreComponents': 'Components',
  'ui.maintenance.restoreType': 'Type',
  'ui.maintenance.restoreAndRestart': 'Restore and Restart',
  'ui.maintenance.storage': 'Storage Overview',
  'ui.maintenance.storageApprox': 'App usage is measured from the database (or estimated) and is not a backup size.',
  'ui.maintenance.storagePaths': 'Storage paths',
  'ui.storage.dataDb': 'Main database and business data',
  'ui.storage.dataWal': 'Transaction log of the main database',
  'ui.storage.designerDb': 'Metadata saved through the Designer',
  'ui.storage.designerWal': 'Transaction log of the Designer',
  'ui.storage.backups': 'Backup files',
  'ui.storage.fonts': 'Fonts for reports',
  'ui.storage.liveFiles': 'Attachments in use',
  'ui.storage.archive': 'Archived data and attachments',
  'ui.storage.filesystem': 'Filesystem',
  'ui.storage.total': 'Total',
  'ui.storage.free': 'Free',
  'ui.storage.usageByApp': 'Database usage per App',
  'ui.storage.methodMeasured': 'measured from the database',
  'ui.storage.methodEstimate': 'estimated',
  'ui.maintenance.archive': 'Archive Policy',
  'ui.maintenance.archiveEntity': 'Data Entity',
  'ui.maintenance.archiveEntityHint': 'Document type to archive',
  'ui.archive.businessDateField': 'Business date field',
  'ui.archive.businessDateHint': 'Date used to calculate document age; choose a date/datetime field of the root table.',
  'ui.archive.ageDays': 'Age days',
  'ui.archive.batchSize': 'Batch size',
  'ui.archive.schedule': 'Schedule',
  'ui.archive.weekday': 'Weekday',
  'ui.archive.timezone': 'Timezone',
  'ui.archive.includeAttachments': 'Include attachments',
  'ui.archive.enabled': 'Enabled',
  'ui.archive.enabledHint': 'The scheduler checks hourly; enabling may start a run on the next check.',
  'ui.archive.policySaved': 'Archive policy saved',
  'ui.archive.restored': 'Archived document restored',
  'ui.archive.skipped': 'Document skipped',
  'ui.archive.oldest': 'oldest',
  'ui.archive.cutoff': 'cutoff',
  'ui.archive.runNotice': 'Documents are moved out of the live tables into the archive. This cannot be undone from this page.',
  'ui.archive.weekdaySun': 'Sunday',
  'ui.archive.weekdayMon': 'Monday',
  'ui.archive.weekdayTue': 'Tuesday',
  'ui.archive.weekdayWed': 'Wednesday',
  'ui.archive.weekdayThu': 'Thursday',
  'ui.archive.weekdayFri': 'Friday',
  'ui.archive.weekdaySat': 'Saturday',
  'ui.archive.savePolicy': 'Save policy',
  'ui.archive.preview': 'Preview',
  'ui.archive.run': 'Archive batch',
  'ui.archive.unsaved': 'Save the policy before previewing or archiving.',
  'ui.archive.confirmTitle': 'Archive documents now?',
  'ui.archive.saveEnabledNotice': 'Enabling automatic archiving may start a run on the next hourly scheduler check. Save anyway?',
  'ui.archive.empty': 'No archive-eligible Data Entity yet. Create a Data Entity with a business date field in the Designer.',
  'ui.archive.documents': 'Archived documents (read-only)',
  'ui.archive.jobs': 'Job history',
  'ui.archive.restore': 'Restore',
  'ui.archive.view': 'View',
  'ui.backup.full': 'Full — Data + Designer + Fonts + Files + Archive',
  'ui.backup.data': 'Data database',
  'ui.backup.designer': 'Designer database',
  'ui.backup.fonts': 'Report fonts',
  'ui.backup.files': 'Live attachments',
  'ui.backup.archive': 'Archive catalog and payloads',
  'ui.designer.title': 'Builder',
  'ui.designer.new': 'New',
  'ui.designer.save': 'Save',
  'ui.designer.saved': 'Saved — changes are live',
  'ui.designer.back': 'Back',
  'ui.designer.designTab': 'Design',
  'ui.designer.jsonTab': 'JSON',
  'ui.designer.name': 'Name',
  'ui.designer.label': 'Label',
  'ui.designer.app': 'App',
  'ui.designer.model': 'Model',
  'ui.designer.layer': 'Layer',
  'ui.designer.search': 'Search artifacts',
  'ui.designer.appDefaultLocale': 'Default language',
  'ui.designer.appDefaultLocaleHint': 'Labels fall back to this locale when the user language has no translation.',
  'ui.designer.kind.app': 'App',
  'ui.designer.kind.table': 'Table (+ form + menu)',
  'ui.designer.kind.enum': 'Enum',
  'ui.designer.kind.form': 'Form',
  'ui.designer.kind.menu': 'Menu',
  'ui.designer.kind.privilege': 'Privilege',
  'ui.designer.kind.duty': 'Duty',
  'ui.designer.kind.role': 'Role',
  'ui.designer.kind.report': 'Report',
  'ui.designer.kind.view': 'View (query / data source)',
  'ui.designer.kind.chart': 'Chart',
  'ui.designer.kind.script': 'Script',
  'ui.designer.kind.function': 'Function',
  'ui.designer.kind.dataEntity': 'Data Entity',
  'ui.designer.kind.translation': 'Translation',
  'ui.designer.kind.extensionSuffix': 'Extension',
  'ui.designer.translation.locale': 'Locale',
  'ui.designer.translation.target': 'Target',
  'ui.designer.translation.defaultText': 'Default text',
  'ui.designer.translation.translation': 'Translation',
  'ui.designer.translation.status': 'Status',
  'ui.designer.translation.translated': 'Translated',
  'ui.designer.translation.untranslated': 'Untranslated',
  'ui.designer.translation.showUntranslated': 'Show untranslated only',
  'ui.designer.translation.allCategories': 'All categories',
  'ui.designer.translation.copyDefaults': 'Copy default texts',
  'ui.designer.translation.resourceKey': 'Resource key',
  'ui.designer.translation.empty': 'No translatable targets found for this app and model.',
  'ui.designer.translation.noLocaleWarning': 'No translation resources exist for this locale yet.',
  'ui.designer.translation.staleKeys': 'Saved keys without a current metadata target',
  'ui.designer.dataEntity.rootTable': 'Root table',
  'ui.designer.dataEntity.businessKey': 'Business key',
  'ui.designer.dataEntity.fields': 'Fields',
  'ui.designer.dataEntity.lines': 'Lines',
  'ui.designer.dataEntity.archiveEligible': 'Archive eligible',
  'ui.designer.dataEntity.businessDateField': 'Business date field',
  'ui.designer.dataEntity.addLine': '+ Add line',
  'ui.designer.dataEntity.extensionFields': 'Additional root fields',
  'ui.designer.dataEntity.lineExtensions': 'Additional fields on existing lines',
};

export const FRAMEWORK_UI_TH: Record<string, string> = {
  'ui.nav.settings': 'การตั้งค่า',
  'ui.nav.recent': 'เปิดล่าสุด',
  'ui.nav.recentEmpty': 'ยังไม่มีรายการที่เปิดล่าสุด',
  'ui.nav.openMenu': 'เปิดเมนูนำทาง',
  'ui.nav.collapseMenu': 'ยุบเมนูนำทาง',
  'ui.nav.systemMaintenance': 'การดูแลระบบ',
  'ui.nav.appData': 'จัดการข้อมูลแอป',
  'ui.nav.reportFonts': 'ฟอนต์รายงาน',
  'ui.nav.smtp': 'การตั้งค่า SMTP',
  'ui.nav.usersSecurity': 'ผู้ใช้และความปลอดภัย',
  'ui.nav.changePassword': 'เปลี่ยนรหัสผ่าน',
  'ui.auth.logout': 'ออกจากระบบ',
  'ui.auth.changePassword': 'เปลี่ยนรหัสผ่าน',
  'ui.auth.language': 'ภาษา',
  'ui.auth.localeSaved': 'เปลี่ยนภาษาเรียบร้อย',
  'ui.auth.localePartial': 'บันทึกภาษาแล้ว แต่โหลดข้อความใหม่ไม่สำเร็จ',
  'ui.home.title': 'แอป',
  'ui.home.subtitle': 'เลือกแอปเพื่อเริ่มงานต่อ',
  'ui.home.emptyTitle': 'สร้างแอปธุรกิจแรกของคุณ',
  'ui.home.emptyDescription': 'เริ่มจาก entity ฟิลด์ หน้าจอ และเมนู โดยไม่ต้องเขียน JSON',
  'ui.home.create': 'สร้างแอปแรกของคุณ',
  'ui.common.save': 'บันทึก',
  'ui.common.back': 'ย้อนกลับ',
  'ui.common.cancel': 'ยกเลิก',
  'ui.common.delete': 'ลบ',
  'ui.common.close': 'ปิด',
  'ui.common.download': 'ดาวน์โหลด',
  'ui.common.search': 'ค้นหา',
  'ui.common.retry': 'ลองใหม่',
  'ui.common.unknown': 'ไม่ทราบ',
  'ui.attachments.title': 'ไฟล์แนบ',
  'ui.attachments.upload': 'อัปโหลดไฟล์',
  'ui.attachments.notePlaceholder': 'เพิ่มโน้ต',
  'ui.attachments.addNote': 'เพิ่มโน้ต',
  'ui.attachments.urlPlaceholder': 'https://…',
  'ui.attachments.addUrl': 'เพิ่มลิงก์',
  'ui.attachments.empty': 'ไม่มีไฟล์แนบ',
  'ui.attachments.deleteConfirm': 'ลบไฟล์แนบนี้?',
  'ui.attachments.uploaded': 'อัปโหลดไฟล์แนบแล้ว',
  'ui.attachments.preview': 'เปิดดูรูป',
  'ui.attachments.previewFailed': 'ไม่สามารถแสดงรูปได้',
  'ui.attachments.imageAlt': 'ตัวอย่างรูปภาพ',
  'ui.maintenance.title': 'การดูแลระบบ',
  'ui.maintenance.subtitle': 'อัปเดตเฟรมเวิร์กและสร้างจุดกู้คืนที่ตรวจสอบแล้ว',
  'ui.maintenance.update': 'อัปเดตเฟรมเวิร์ก',
  'ui.maintenance.current': 'เวอร์ชันปัจจุบัน',
  'ui.maintenance.latest': 'เวอร์ชันล่าสุด',
  'ui.maintenance.deployment': 'การติดตั้ง',
  'ui.maintenance.lastChecked': 'ตรวจสอบล่าสุด',
  'ui.maintenance.notChecked': 'ยังไม่ได้ตรวจสอบ',
  'ui.maintenance.checkUpdate': 'ตรวจสอบอัปเดต',
  'ui.maintenance.updateLatest': 'อัปเดตเป็นเวอร์ชันเสถียรล่าสุด',
  'ui.maintenance.upToDate': 'เฟรมเวิร์กเป็นเวอร์ชันล่าสุดแล้ว',
  'ui.maintenance.updateStarted': 'สร้างไฟล์สำรองแล้ว เริ่มอัปเดตเฟรมเวิร์ก',
  'ui.maintenance.updateDisabled': 'การอัปเดตผ่านเว็บไม่ได้ตั้งค่าสำหรับการติดตั้งนี้ ใช้คู่มืออัปเดตด้วยมือ',
  'ui.maintenance.updateTitle': 'อัปเดตเฟรมเวิร์ก?',
  'ui.maintenance.updateConfirm': 'สร้างไฟล์สำรองและอัปเดต',
  'ui.maintenance.updateBody': 'แอปจะสร้างไฟล์สำรองที่ตรวจสอบแล้ว ติดตั้งเวอร์ชันล่าสุด และรีสตาร์ท ผู้ใช้จะเข้าใช้งานไม่ได้ชั่วคราว อย่าปิดเครื่องระหว่างการอัปเดต',
  'ui.maintenance.backup': 'สำรองข้อมูล',
  'ui.maintenance.backupDescription': 'สร้างแพ็กเกจกู้คืนที่มี checksum หรือกู้คืนคอมโพเนนต์ระบบที่เลือกทั้งหมดจากหน้านี้',
  'ui.maintenance.backupComponent': 'ข้อมูลที่ต้องการสำรอง',
  'ui.maintenance.backupComponentHint': 'เลือกคอมโพเนนต์แล้วกดดาวน์โหลดไฟล์สำรองจึงเริ่มทำงาน ส่วนการอัปโหลดและกู้คืนใช้คอมโพเนนต์จากแพ็กเกจที่อัปโหลด',
  'ui.maintenance.downloadBackup': 'ดาวน์โหลดไฟล์สำรอง',
  'ui.maintenance.uploadRestore': 'อัปโหลดและกู้คืน',
  'ui.maintenance.backupReady': 'พร้อมกู้คืน',
  'ui.maintenance.restoreStarted': 'เริ่มการกู้คืน แอปจะรีสตาร์ทอัตโนมัติ',
  'ui.maintenance.restoreBody': 'แอปจะใช้งานไม่ได้ชั่วคราว คอมโพเนนต์ที่เลือกจะถูกแทนที่แบบ atomic และย้อนกลับหากการตรวจสอบหลังรีสตาร์ทไม่ผ่าน',
  'ui.maintenance.restoreComponents': 'คอมโพเนนต์',
  'ui.maintenance.restoreType': 'พิมพ์',
  'ui.maintenance.restoreAndRestart': 'กู้คืนและรีสตาร์ท',
  'ui.maintenance.storage': 'ภาพรวมพื้นที่จัดเก็บ',
  'ui.maintenance.storageApprox': 'การใช้งานของแอปเป็นค่าที่วัดจากฐานข้อมูล (หรือประมาณการ) ไม่ใช่ขนาดไฟล์สำรองข้อมูลทั้งหมด',
  'ui.maintenance.storagePaths': 'ตำแหน่งจัดเก็บ',
  'ui.storage.dataDb': 'ฐานข้อมูลหลักและข้อมูลธุรกิจ',
  'ui.storage.dataWal': 'Transaction log ของฐานข้อมูลหลัก',
  'ui.storage.designerDb': 'Metadata ที่บันทึกผ่าน Designer',
  'ui.storage.designerWal': 'Transaction log ของ Designer',
  'ui.storage.backups': 'ไฟล์สำรองข้อมูล',
  'ui.storage.fonts': 'ฟอนต์สำหรับรายงาน',
  'ui.storage.liveFiles': 'ไฟล์แนบที่ใช้งานอยู่',
  'ui.storage.archive': 'ข้อมูลและไฟล์แนบที่เก็บถาวร',
  'ui.storage.filesystem': 'ระบบไฟล์',
  'ui.storage.total': 'ทั้งหมด',
  'ui.storage.free': 'ว่าง',
  'ui.storage.usageByApp': 'การใช้งานฐานข้อมูลต่อแอป',
  'ui.storage.methodMeasured': 'วัดจากฐานข้อมูล',
  'ui.storage.methodEstimate': 'ประมาณการ',
  'ui.maintenance.archive': 'นโยบายจัดเก็บถาวร',
  'ui.maintenance.archiveEntity': 'Data Entity',
  'ui.maintenance.archiveEntityHint': 'ประเภทเอกสารที่ต้องการจัดเก็บ',
  'ui.archive.businessDateField': 'ฟิลด์วันที่ทางธุรกิจ',
  'ui.archive.businessDateHint': 'วันที่ที่ใช้คำนวณอายุเอกสาร เลือกจากฟิลด์แบบวันที่ของตารางหลัก',
  'ui.archive.ageDays': 'อายุขั้นต่ำ (วัน)',
  'ui.archive.batchSize': 'จำนวนเอกสารสูงสุดต่อรอบ',
  'ui.archive.schedule': 'กำหนดการ',
  'ui.archive.weekday': 'วันในสัปดาห์',
  'ui.archive.timezone': 'เขตเวลา',
  'ui.archive.includeAttachments': 'รวมไฟล์แนบ',
  'ui.archive.enabled': 'เปิดใช้งานอัตโนมัติ',
  'ui.archive.enabledHint': 'ตัวกำหนดตารางตรวจทุกชั่วโมง การเปิดใช้งานอาจเริ่มทำงานในรอบตรวจถัดไป',
  'ui.archive.policySaved': 'บันทึกนโยบายเก็บถาวรแล้ว',
  'ui.archive.restored': 'กู้คืนเอกสารแล้ว',
  'ui.archive.skipped': 'ข้ามเอกสารนี้',
  'ui.archive.oldest': 'เก่าสุด',
  'ui.archive.cutoff': 'วันตัด',
  'ui.archive.runNotice': 'เอกสารจะถูกย้ายออกจากตารางใช้งานเข้าที่เก็บถาวร ไม่สามารถย้อนกลับจากหน้านี้ได้',
  'ui.archive.weekdaySun': 'อาทิตย์',
  'ui.archive.weekdayMon': 'จันทร์',
  'ui.archive.weekdayTue': 'อังคาร',
  'ui.archive.weekdayWed': 'พุธ',
  'ui.archive.weekdayThu': 'พฤหัสบดี',
  'ui.archive.weekdayFri': 'ศุกร์',
  'ui.archive.weekdaySat': 'เสาร์',
  'ui.archive.savePolicy': 'บันทึกนโยบาย',
  'ui.archive.preview': 'ดูตัวอย่าง',
  'ui.archive.run': 'เก็บถาวรทันที',
  'ui.archive.unsaved': 'ต้องบันทึกนโยบายก่อนดูตัวอย่างหรือเก็บถาวร',
  'ui.archive.confirmTitle': 'เก็บถาวรเอกสารตอนนี้?',
  'ui.archive.saveEnabledNotice': 'การเปิดใช้งานอัตโนมัติอาจเริ่มทำงานในรอบตรวจถัดไป บันทึกเพื่อ?',
  'ui.archive.empty': 'ยังไม่มี Data Entity ที่เก็บถาวรได้ สร้าง Data Entity พร้อมฟิลด์วันที่ทางธุรกิจใน Designer',
  'ui.archive.documents': 'เอกสารที่เก็บถาวร (อ่านอย่างเดียว)',
  'ui.archive.jobs': 'ประวัติงาน',
  'ui.archive.restore': 'กู้คืน',
  'ui.archive.view': 'ดู',
  'ui.backup.full': 'ทั้งหมด — ข้อมูล + Designer + ฟอนต์ + ไฟล์แนบ + Archive',
  'ui.backup.data': 'ฐานข้อมูลข้อมูล',
  'ui.backup.designer': 'ฐานข้อมูล Designer',
  'ui.backup.fonts': 'ฟอนต์รายงาน',
  'ui.backup.files': 'ไฟล์แนบที่ใช้งานอยู่',
  'ui.backup.archive': 'แคตตาล็อกและไฟล์ Archive',
  'ui.designer.title': 'ตัวสร้างแอป',
  'ui.designer.new': 'สร้างใหม่',
  'ui.designer.save': 'บันทึก',
  'ui.designer.saved': 'บันทึกแล้ว — การเปลี่ยนแปลงใช้งานได้ทันที',
  'ui.designer.back': 'ย้อนกลับ',
  'ui.designer.designTab': 'ออกแบบ',
  'ui.designer.jsonTab': 'JSON',
  'ui.designer.name': 'ชื่อ',
  'ui.designer.label': 'ป้ายชื่อ',
  'ui.designer.app': 'แอป',
  'ui.designer.model': 'โมเดล',
  'ui.designer.layer': 'เลเยอร์',
  'ui.designer.search': 'ค้นหา artifact',
  'ui.designer.appDefaultLocale': 'ภาษาหลัก',
  'ui.designer.appDefaultLocaleHint': 'ป้ายชื่อจะ fallback ไปภาษานี้เมื่อภาษาของผู้ใช้ยังไม่มีคำแปล',
  'ui.designer.kind.app': 'แอป',
  'ui.designer.kind.table': 'ตาราง (+ ฟอร์ม + เมนู)',
  'ui.designer.kind.enum': 'Enum',
  'ui.designer.kind.form': 'ฟอร์ม',
  'ui.designer.kind.menu': 'เมนู',
  'ui.designer.kind.privilege': 'สิทธิ์ (Privilege)',
  'ui.designer.kind.duty': 'หน้าที่ (Duty)',
  'ui.designer.kind.role': 'บทบาท (Role)',
  'ui.designer.kind.report': 'รายงาน',
  'ui.designer.kind.view': 'View (คิวรี / แหล่งข้อมูล)',
  'ui.designer.kind.chart': 'แผนภูมิ',
  'ui.designer.kind.script': 'สคริปต์',
  'ui.designer.kind.function': 'ฟังก์ชัน',
  'ui.designer.kind.dataEntity': 'Data Entity',
  'ui.designer.kind.translation': 'คำแปล (Translation)',
  'ui.designer.kind.extensionSuffix': 'ส่วนขยาย',
  'ui.designer.translation.locale': 'ภาษา',
  'ui.designer.translation.target': 'เป้าหมาย',
  'ui.designer.translation.defaultText': 'ข้อความเดิม',
  'ui.designer.translation.translation': 'คำแปล',
  'ui.designer.translation.status': 'สถานะ',
  'ui.designer.translation.translated': 'แปลแล้ว',
  'ui.designer.translation.untranslated': 'ยังไม่แปล',
  'ui.designer.translation.showUntranslated': 'แสดงเฉพาะที่ยังไม่แปล',
  'ui.designer.translation.allCategories': 'ทุกหมวด',
  'ui.designer.translation.copyDefaults': 'คัดลอกข้อความเดิม',
  'ui.designer.translation.resourceKey': 'resource key',
  'ui.designer.translation.empty': 'ไม่พบเป้าหมายที่แปลได้สำหรับแอปและโมเดลนี้',
  'ui.designer.translation.noLocaleWarning': 'ยังไม่มี resource ของภาษานี้',
  'ui.designer.translation.staleKeys': 'key ที่บันทึกไว้แต่ไม่มีเป้าหมายปัจจุบัน',
  'ui.designer.dataEntity.rootTable': 'ตารางหลัก',
  'ui.designer.dataEntity.businessKey': 'Business key',
  'ui.designer.dataEntity.fields': 'ฟิลด์',
  'ui.designer.dataEntity.lines': 'รายการลูก',
  'ui.designer.dataEntity.archiveEligible': 'เก็บถาวรได้',
  'ui.designer.dataEntity.businessDateField': 'ฟิลด์วันที่ทางธุรกิจ',
  'ui.designer.dataEntity.addLine': '+ เพิ่มรายการลูก',
  'ui.designer.dataEntity.extensionFields': 'ฟิลด์เพิ่มเติมของตารางหลัก',
  'ui.designer.dataEntity.lineExtensions': 'ฟิลด์เพิ่มเติมของรายการลูกที่มีอยู่',
};
