<script setup lang="ts">
import { ref } from 'vue';
import { NAlert, NButton, NModal, NSpace, useMessage } from 'naive-ui';
import { api, ApiError, requestForm } from '../api';
const props=defineProps<{show:boolean;entityName:string}>(); const emit=defineEmits<{(event:'update:show',value:boolean):void;(event:'imported'):void}>(); const message=useMessage(); const file=ref<File|null>(null); const preview=ref<{previewId:string;documents:number;sources:{name:string;rows:number}[]}|null>(null); const busy=ref(false); const result=ref<Record<string,unknown>|null>(null);
async function select(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]??null;preview.value=null;result.value=null;if(!file.value)return;busy.value=true;try{const form=new FormData();form.append('file',file.value);preview.value=await requestForm(`/api/data-entities/${encodeURIComponent(props.entityName)}/import/preview`,form);}catch(error){message.error(error instanceof ApiError?error.message:String(error));}finally{busy.value=false;}}
async function commit(){if(!preview.value)return;busy.value=true;try{result.value=await api.post(`/api/data-entities/${encodeURIComponent(props.entityName)}/import/commit`,{previewId:preview.value.previewId});message.success('Data Entity import completed');emit('imported');}catch(error){message.error(error instanceof ApiError?error.message:String(error));}finally{busy.value=false;}}
</script>
<template><n-modal :show="show" preset="card" :title="`Import ${entityName}`" style="width:min(720px,94vw)" @update:show="emit('update:show',$event)"><n-space vertical size="large"><p>Use XLSX (Header and line sheets) or a CSV ZIP package exported by this Data Entity. Each document commits atomically.</p><input type="file" accept=".xlsx,.zip" @change="select"><n-alert v-if="preview" type="info">{{ preview.documents }} documents · {{ preview.sources.map(source=>`${source.name}: ${source.rows}`).join(' · ') }}</n-alert><n-alert v-if="result" :type="Number(result.failed)?'warning':'success'"><pre>{{ JSON.stringify(result,null,2) }}</pre><a v-if="result.errorFile" :href="String(result.errorFile)">Download error file</a></n-alert><n-space justify="end"><n-button @click="emit('update:show',false)">Close</n-button><n-button type="primary" :disabled="!preview" :loading="busy" @click="commit">Commit import</n-button></n-space></n-space></n-modal></template>
